version: 2
jobs:
  build:
    docker:
      - image: jloh/geojs-tests:latest
    steps:
      - checkout
      # We have to do it this way since wget'ing it lands us weird dir names
      - run:
          name: 'Download GoeLite2 Maxmind DBs'
          command: |
            mkdir -p download-cache/maxmind2
            cp .circleci/Geoip.conf /etc/GeoIP.conf
            echo "AccountID $MAXMIND_ACCOUNT_ID" >> /etc/GeoIP.conf
            echo "LicenseKey $MAXMIND_TOKEN" >> /etc/GeoIP.conf
            geoipupdate -v
      - run:
          name: 'Add in Maxmind ASN'
          command: |
            mkdir -p lib/resty
            curl -s -o lib/resty/maxminddb_asn.lua $MAXMIND_LUA_URL
      - run:
          name: 'Openresty version'
          command: openresty -V
      - run:
          name: 'Link openresty for tests'
          command: ln -s /usr/bin/openresty /usr/bin/nginx
      - run:
          name: 'Directory for test results'
          command: mkdir -p test-results/prove
      - run:
          name: 'Tests'
          command: prove -r t -a test_results.tgz --formatter TAP::Formatter::JUnit > test-results/prove/nosetests.xml
      - run:
          name: 'Test Coverage'
          command: |
            if [[ "${TEST_COVERAGE}x" == '1x' ]]; then luacov; fi
            if [[ "${TEST_COVERAGE}x" == '1x' ]]; then luacov-coveralls; fi
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test_results.tgz
      - store_artifacts:
          path: test-results/
